services:
  authservice:
    container_name: auth-service
    build:
      context: ./backend
      dockerfile: ./AuthService/Dockerfile
    expose:
      - "8080"
    networks:
      - job-network
  
  userservice:
    container_name: user-service
    build:
      context: ./backend
      dockerfile: ./UserService/Dockerfile
    expose:
      - "8080"
    networks:
      - job-network
  
  jobservice:
    container_name: job-service
    build:
      context: ./backend
      dockerfile: ./JobService/Dockerfile
    expose:
      - "8080"
    networks:
      - job-network

  nginx:
    container_name: backend-nginx
    image: nginx:1.28.0
    volumes:
      - ./backend/nginx/local_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - authservice
      - userservice
      - jobservice
    networks:
      - job-network
  
  frontend:
    container_name: frontend-react
    build:
      context: ./frontend/job-listing-app/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - job-network

  mysql:
    container_name: mysql-joblisting
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: JobListingDB
    volumes:
      - JobListingDBVolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - job-network

networks:
  job-network:

volumes:
  JobListingDBVolume:
