services:
  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    expose:
      - "8080"
    networks:
      - backend-network

  nginx:
    image: nginx:1.28.0
    volumes:
      - ./nginx/local_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - authservice
    networks:
      - backend-network
  
  mysql:
    image: mysql:9.2.0
    container_name: joblisting-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: JobListingDB
    volumes:
      - JobListingDBVolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  JobListingDBVolume:
